server:
  port: ${portMSPatrones}
  
logging:
  file: ${fileLogPatrones}  
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
    mx.gob.imss.cit.pmc: DEBUG
    com.netflix: WARN